Created hitl session module (controller, repository, service, model and routes)
DigiSenseiZim/Chatgate-backend-v1 pull request #4
Opened 2024-11-06 13:33 UTC by divah21

2024-11-07 09:02 UTC, DigiSenseiZim requested changes
Apply all the changes in the comments, test then push. On cloning your repo and adding my own `.env` in a similar environment I was unable to fire the API up.

2024-11-08 05:44 UTC, divah21 commented on src/controllers/hitlMessagesController.js
all comments resolved in HitlMessageController

2024-11-11 06:10 UTC, divah21 commented on src/repositories/hitlMessagesRepository.js
comments addressed

2024-11-11 06:11 UTC, divah21 commented on src/controllers/hitlSessionController.js
comments resolved

2024-11-11 10:33 UTC, DigiSenseiZim approved these changes

2024-11-11 10:34 UTC, DigiSenseiZim approved these changes

2024-11-11 10:34 UTC, merged